using ArchLens.SharedKernel.Domain;
using FluentAssertions;

namespace ArchLens.SharedKernel.Tests.Domain;

public class DomainEventTests
{
    private sealed record TestEvent(string Message) : DomainEvent;

    [Fact]
    public void EventId_ShouldBeAutoGenerated()
    {
        var domainEvent = new TestEvent("test");

        domainEvent.EventId.Should().NotBe(Guid.Empty);
    }

    [Fact]
    public void EventId_TwoEvents_ShouldBeDifferent()
    {
        var event1 = new TestEvent("test1");
        var event2 = new TestEvent("test2");

        event1.EventId.Should().NotBe(event2.EventId);
    }

    [Fact]
    public void OccurredAt_ShouldBeAutoSet()
    {
        var before = DateTime.UtcNow;
        var domainEvent = new TestEvent("test");
        var after = DateTime.UtcNow;

        domainEvent.OccurredAt.Should().BeOnOrAfter(before);
        domainEvent.OccurredAt.Should().BeOnOrBefore(after);
    }

    [Fact]
    public void DomainEvent_ShouldImplementIDomainEvent()
    {
        var domainEvent = new TestEvent("test");

        domainEvent.Should().BeAssignableTo<IDomainEvent>();
    }

    [Fact]
    public void DomainEvent_Properties_ShouldBePreserved()
    {
        var domainEvent = new TestEvent("hello");

        domainEvent.Message.Should().Be("hello");
    }
}
